module.exports = {
  accessors: {
    Movie: {
      key: 'ratingKey',
      guid: true,
      studio: true,
      title: true,
      sortTitle: 'titleSort',
      contentRating: true,
      summary: true,
      rating: true,
      audienceRating: true,
      year: true,
      tagline: true,
      duration: true,
      originallyAvailableAt: true,
      addedAt: true,
      updatedAt: true,
      thumbnail: 'thumb',
      poster: 'art',
      audienceRatingImage: true,
      ratingImage: true,
    },
    Version: {
      id: true,
      duration: true,
      bitrate: true,
      aspectRatio: true,
      resolution: 'videoResolution',
    },
    Part: {
      id: true,
      duration: true,
      file: true,
      size: true,
      container: true,
    },
    Video: {
      id: true,
      default: true,
      codec: true,
      bitrate: true,
      frameRate: true,
      height: true,
      profile: true,
      width: true,
      title: 'displayTitle',
    },
    Audio: {
      id: true,
      default: true,
      codec: true,
      channels: true,
      channelLayout: 'audioChannelLayout',
      bitrate: true,
      langauge: true,
      languageCode: true,
      profile: true,
      title: 'displayTitle',
    },
    Subtitle: {
      id: true,
      file: true,
      codec: true,
      language: true,
      languageCode: true,
      format: true,
      title: 'displayTitle',
    },
    Genre: { id: true, name: 'tag' },
    Director: { id: true, name: 'tag' },
    Writer: { id: true, name: 'tag' },
    Producer: { id: true, name: 'tag' },
    Country: { id: true, name: 'tag' },
    Guid: { id: true, agent: true },
    Collection: { id: true, name: 'tag' },
    Actor: { id: true, name: 'tag', image: 'thumb' },
    Review: {
      id: true,
      name: 'tag',
      text: true,
      image: true,
      link: true,
      source: true,
    },
  },
};
